brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "jq"
brew "navi"
brew "ripgrep"
brew "tmux"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "codex"
cask "font-jetbrains-mono-nerd-font"
